[package]
name = "part-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow="1.0.66"
regex = "1.7.0"
itertools = "0.8"
queues = "1.0.2"